version: '3.8'  # Docker Compose file version

services:
  backend:
    image: openjdk:17  # Use an OpenJDK image for Spring Boot
    container_name: non-academic-backend
    build:
      context: D:/Study/work_doc/SpringBoot/Non-academicWebsite/Non-academicWebsite  # Path to Spring Boot project directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose port 8080 to the host
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/non_academic_staff?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD="#Passwd10"
    depends_on:
      - mysql-db  # Ensure the database service is started first

  frontend:
    image: node:18-alpine  # Use a Node image for React
    container_name: non-academic-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app  # Mount frontend directory
    ports:
      - "3000:3000"  # Expose port 3000 to the host
    command: sh -c "npm install && npm start"

  mysql-db:
    image: mysql:8
    container_name: non_academic_staff-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="#Vithu10"
      - MYSQL_DATABASE=non_academic_staff
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:  # Volume to persist database data
